### ISSUE TITLE
2017.1.5 compatibility? 

### ISSUE THREAD

**Issue by MostHated** [Nobinator/Unity-Editor-ListView#2]
Hey there,
    I was wondering if this should be able to work in 2017.1.5? I imported it but it is giving me the error of: 

```cs
Assets/instance.id/AnimEditor/open-source/Unity-Editor-ListView/ListView.cs(78,33): error CS0115: `ListView.ListView<T>.SingleClickedItem(int)' is marked as an override but no suitable method found to override

```

I guess a base class must be missing from this version? : (
Thanks,
-MH
